version: 2.1

executors:
  macos-exec:
    macos:
      xcode: "16.0.0"
    resource_class: macos.m1.medium

jobs:
  build-mac:
    executor: macos-exec
    steps:
      - checkout
      - run:
          name: Verify nvm Installation and Install Node.js v18
          command: |
            if ! command -v nvm &> /dev/null; then
              echo "nvm could not be found, installing..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            fi
            nvm install v18.18.0
            nvm use v18.18.0
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build & Package macOS App
          command: npm run dist:macArm
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/builds

workflows:
  build:
    jobs:
      - build-mac
